server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vegetable_sales?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: a1b4c6d9
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: UTF-8
    content-type: text/html
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.farm.vegetablesales.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.farm.vegetablesales: debug
    org.mybatis: DEBUG
    com.alibaba.druid: DEBUG